### PR TITLE
npm publication

### PR DESCRIPTION
**Pull request by jrouault**
In order to prepare for npm publication some major changes were made to the repo:
- Clean repo to match classic Cordova plugin structure: basically the test app was removed, some other ways to test will be added later on. It could simply be to restore the test app, but it should no longer entirely sits in the repo.
- Rename plugin to cordova-plugin-wizpurchase: this is the actual convention regarding Cordova plugin naming. This is not mandatory but it seems to be the right thing to do. It implies to rename this repo as well once the PR merged.
- Add package.json for npm publication

NB: To help reviewing the first commit references all the changes: moved files, renaming, etc. The second commit is only deleted files.

poke @ronkorving and @aogilvie

### CODE REVIEW

**Comment by ronkorving** [comment]
Why the uppercase in JS-land? That's not a style I ever really see for singletons.

**Comment by jrouault** [comment]
Hmm, yeah, right, I'll revert that. It doesn't make much sense.

**Comment by jrouault** [comment]
Updated, any other concerns?

**Comment by ronkorving** [comment]
Nope :+1:

**Pull request merged**
